---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрироваться
  - Доступность пользователям с ограниченными возможностями #Доступность. Требования к доступности сайта для пользователей с ограниченными возможностями. Обеспечивает равные возможности для всех пользователей, повышает доступность информации.
  - Пользователи должны иметь возможность использовать встроенную клавиатуру своего телефона для заполнения поля
  - Поле регистрации должно предупреждать пользователей, если они не заполняют поле
  - Поле регистрации не должно позволять регистрироваться, пока поле не заполненно
  - Сайт должен иметь адаптивную верстку мобильной версии
  - Текст блоков должен быть на одном языке
  - Цена на товар должна отображаться в валюте выбранной страны
  - Раздел боковой панели Категория должн иметь функцию отмены выбора всех категорий
  - Сайт должен иметь форму обратной связи 
  - Пользователь иметь возможность просматривать заказ
  - Боковая панель не должна перемещаться вместе с разделом товаров
  - Верхняя панель не должна перемещаться вместе с разделом товаров
  - Ссылки должны открываться в новом окне/вкладке при нажатии левой кнопки мыши #если не указано другое
  - Логотип компании компании должен быть интеактивным #если не указано иное
  - Ширина выпадающего списка должна быть достаточной  для самого длинного значения
  - Если текст на сайте есть неполный текст, то при наведении на него курсором мыши должен отображаться текст целиком
  - Обязательные поля должны обозначаться звездочкой #если не указано другое
  - Выпадающий список должен быть выделен серым цветом
  - Копирование и вставка значений в поле пароля должны быть запрещены
  - Всегда указывать типы файлов, которые могут быть загружены
  - Максимальный размер файла должен быть опеделен заранее
  - В мобильной версии текст  и ссылки не должны быть мелкими
  - Ширина поля В корзину в блоке с товаром должны быть одинаковыми по ширине и высоте
