---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрироваться
  - Доступность пользователям с ограниченными возможностями #Доступность. Требования к доступности сайта для пользователей с ограниченными возможностями. Обеспечивает равные возможности для всех пользователей, повышает доступность информации.
  - Пользователи должны иметь возможность использовать встроенную клавиатуру своего телефона для заполнения поля
  - Поле должно предупреждать пользователей, если они не заполняют поле номера телефона, и не позволять им заполнять форму, пока они этого не сделают
